jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      node_6_x:
        node_version: 6.x
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
    maxParallel: 3
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node.js'

  - script: npm install -g pnpm
    displayName: 'Install pnpm'
  - script: pnpm recursive install
    displayName: 'Install dependencies'
  - script: pnpm recursive test --workspace-concurrency 1
    displayName: 'Run tests'
