packages:
  - '**'
  - '!**/test/**'
  - '!**/node_modules_link/**'
allowBuilds:
  '@pnpm/exe': true
  bun: true
  core-js: false
  yarn: true

configDependencies:
  '@pnpm/plugin-better-defaults': 0.2.1

overrides:
  '@types/node': 25.4.0
