packages:
  - '**'
  - '!**/test/**'
  - '!resolve-link-target/node_modules_link/**'

overrides:
  '@types/node': 14.14.6

onlyBuiltDependencies:
  - '@pnpm/exe'
  - bun
  - yarn

ignoredBuiltDependencies:
  - core-js

configDependencies:
  '@pnpm/better-defaults': 0.1.0+sha512-ikR/q6RSGqnn+6SSzmVEC+TgYhwb9OMdjkt0G5aNvZivE5SvsKwfK1lW1UDTLTpBqqVuv0duIz8ko0KdoSfcGw==

hoist: true
linkWorkspacePackages: false
saveExact: false
strictPeerDependencies: false

