packages:
  - '**'
  - '!**/test/**'
  - '!resolve-link-target/node_modules_link/**'

configDependencies:
  '@pnpm/plugin-better-defaults': 0.2.1+sha512-3Fmur80S7+vmOKMmTdKS6JofiuvpUaBIdKEpgDyr9571FHo5Z4O2nrRUaSflxvwEakeYxIaFZ5MBaqAUnYHaeg==

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - '@pnpm/exe'
  - bun
  - yarn

overrides:
  '@types/node': 14.14.6
